### ISSUE TITLE
Join Org

### ISSUE THREAD

**Issue by RayyanNafees** [zhcet-code-oasis/code-oasis-website#25]
Hi Guys!

My name is [Rayyan Nafees](https://github.com/RayyanNafees) a [**Fullstack Web Developer**](https://rayyannafees.github.io) with 2 yrs of [industrial working experience](https://drive.google.com/file/d/1YBwZhkDFpqv3NqBW0bnI3Mr7N87KcthS/view?usp=sharing) in the field

I'm 1st yr B.tech student in AMU studying at ZHCET and would love to contribute to the project with my skills to this organisation

It's been 8 months I've been doing projects with Astro and am sure my expertise will come in handy for the development of this organisation & in particular this project. So would like to Join the Organisation

Hope to hear from u soon
Regards

**Comment by rajuljha** [comment]
Hey @RayyanNafees . Great to hear from you! Welcome!
In order to join the organisation create an issue in the .github repository of the organisation with the name Join Org and add the label <invite me to the organisation> to the issue. Then an invitation email will be sent to you and you can join the organisation.

**Comment by tayyab-ilyas** [comment]
follow this link https://github.com/zhcet-code-oasis/.github/issues/new?assignees=&labels=invite+me+to+the+organization&projects=&template=organization-invitation.md&title=Join+Org

> Hi Guys!
> 
> My name is [Rayyan Nafees](https://github.com/RayyanNafees) a [**Fullstack Web Developer**](https://rayyannafees.github.io) with 2 yrs of [industrial working experience](https://drive.google.com/file/d/1YBwZhkDFpqv3NqBW0bnI3Mr7N87KcthS/view?usp=sharing) in the field
> 
> I'm 1st yr B.tech student in AMU studying at ZHCET and would love to contribute to the project with my skills to this organisation
> 
> It's been 8 months I've been doing projects with Astro and am sure my expertise will come in handy for the development of this organisation & in particular this project. So would like to Join the Organisation
> 
> Hope to hear from u soon Regards

**Comment by RayyanNafees** [comment]
Done
